// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: OctoDisplay

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_ScreenSetup
void ui_ScreenSetup_screen_init(void);
lv_obj_t *ui_ScreenSetup;
lv_obj_t *ui_LabelSetupTitle;
lv_obj_t *ui_LabelWiFiNetwork;
lv_obj_t *ui_LabelIPAddress;
lv_obj_t *ui_LabelURL;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenIHD
void ui_ScreenIHD_screen_init(void);
lv_obj_t *ui_ScreenIHD;
lv_obj_t *ui_Label6;
lv_obj_t *ui_PanelGrid;
lv_obj_t *ui_GridPower;
lv_obj_t *ui_GridEnergyIn;
lv_obj_t *ui_GridEnergyOut;
lv_obj_t *ui_GridEnergyOutPrice;
lv_obj_t *ui_GridEnergyInPrice;
lv_obj_t *ui_PanelLoad;
lv_obj_t *ui_LoadPower;
lv_obj_t *ui_LoadEnergy;
lv_obj_t *ui_PanelPV;
lv_obj_t *ui_PVPower;
lv_obj_t *ui_PVEnergy;
lv_obj_t *ui_PanelBattery;
lv_obj_t *ui_BatteryPower;
lv_obj_t *ui_BatteryEnergyIn;
lv_obj_t *ui_BatteryEnergyOut;
lv_obj_t *ui_BatterySOC;
lv_obj_t *ui_BatteryTemp;
lv_obj_t *ui_PanelCar;
lv_obj_t *ui_CarSOC;
lv_obj_t *ui_CarPlug;
lv_obj_t *ui_CarRange;
lv_obj_t *ui_CarMode;
lv_obj_t *ui_CarPower;
lv_obj_t *ui_CarLastCharge;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_ScreenSetup_screen_init();
ui_ScreenIHD_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_ScreenSetup);
}
