// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: OctoDisplay

#ifndef _OCTODISPLAY_UI_H
#define _OCTODISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenSetup
void ui_ScreenSetup_screen_init(void);
extern lv_obj_t *ui_ScreenSetup;
extern lv_obj_t *ui_LabelSetupTitle;
extern lv_obj_t *ui_LabelWiFiNetwork;
extern lv_obj_t *ui_LabelIPAddress;
extern lv_obj_t *ui_LabelURL;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenIHD
void ui_ScreenIHD_screen_init(void);
extern lv_obj_t *ui_ScreenIHD;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_PanelGrid;
extern lv_obj_t *ui_GridPower;
extern lv_obj_t *ui_GridEnergyIn;
extern lv_obj_t *ui_GridEnergyOut;
extern lv_obj_t *ui_GridEnergyOutPrice;
extern lv_obj_t *ui_GridEnergyInPrice;
extern lv_obj_t *ui_PanelLoad;
extern lv_obj_t *ui_LoadPower;
extern lv_obj_t *ui_LoadEnergy;
extern lv_obj_t *ui_PanelPV;
extern lv_obj_t *ui_PVPower;
extern lv_obj_t *ui_PVEnergy;
extern lv_obj_t *ui_PanelBattery;
extern lv_obj_t *ui_BatteryPower;
extern lv_obj_t *ui_BatteryEnergyIn;
extern lv_obj_t *ui_BatteryEnergyOut;
extern lv_obj_t *ui_BatterySOC;
extern lv_obj_t *ui_BatteryTemp;
extern lv_obj_t *ui_PanelCar;
extern lv_obj_t *ui_CarSOC;
extern lv_obj_t *ui_CarPlug;
extern lv_obj_t *ui_CarRange;
extern lv_obj_t *ui_CarMode;
extern lv_obj_t *ui_CarPower;
extern lv_obj_t *ui_CarLastCharge;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
