// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: OctoDisplay

#ifndef _OCTODISPLAY_UI_H
#define _OCTODISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenSetup
void ui_ScreenSetup_screen_init(void);
extern lv_obj_t *ui_ScreenSetup;
extern lv_obj_t *ui_LabelSetupTitle;
extern lv_obj_t *ui_LabelWiFiNetwork;
extern lv_obj_t *ui_LabelIPAddress;
extern lv_obj_t *ui_LabelURL;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenIHD
void ui_ScreenIHD_screen_init(void);
extern lv_obj_t *ui_ScreenIHD;
extern lv_obj_t *ui_Label6;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
