// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: OctoDisplay

#include "ui.h"

void ui_ScreenSetup_screen_init(void)
{
ui_ScreenSetup = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenSetup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelSetupTitle = lv_label_create(ui_ScreenSetup);
lv_obj_set_width( ui_LabelSetupTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSetupTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelSetupTitle, 0 );
lv_obj_set_y( ui_LabelSetupTitle, -100 );
lv_obj_set_align( ui_LabelSetupTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSetupTitle,"Setup Mode");
lv_obj_set_style_text_font(ui_LabelSetupTitle, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelWiFiNetwork = lv_label_create(ui_ScreenSetup);
lv_obj_set_width( ui_LabelWiFiNetwork, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelWiFiNetwork, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelWiFiNetwork, 0 );
lv_obj_set_y( ui_LabelWiFiNetwork, -50 );
lv_obj_set_align( ui_LabelWiFiNetwork, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelWiFiNetwork,"Log on to WiFi Network OctoDisplay");

ui_LabelIPAddress = lv_label_create(ui_ScreenSetup);
lv_obj_set_width( ui_LabelIPAddress, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelIPAddress, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelIPAddress, 0 );
lv_obj_set_y( ui_LabelIPAddress, -21 );
lv_obj_set_align( ui_LabelIPAddress, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelIPAddress,"Go to IP Address");

ui_LabelURL = lv_label_create(ui_ScreenSetup);
lv_obj_set_width( ui_LabelURL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelURL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelURL, -2 );
lv_obj_set_y( ui_LabelURL, 11 );
lv_obj_set_align( ui_LabelURL, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelURL,"Visit: http://192.168.4.1");

}
